Overhaul the entire library.
This commit is a "complete" overhaul of libdevuansdk and is a likely
breaking change for all the sdks. They will be updated accordingly.

Notable changes:
    * Bootstrap tarballs are now cpio archives.
    * Error handling is improved a lot.
    * rsync is avoided and cpio is used where necessary.
    * debootstrap submodule is removed and system-wide debootstrap is
      used instead.
    * VMs aren't being built inside an nbd device anymore. They are now
      built normally on the filesystem, and copied into a raw image
      which is then converted to requested formats (qcow and/or vdi).
    * Vagrant build support is completely dropped.
    * apt-cache functionality is completely dropped.
    * The full-build helper functions are renamed and and separated into
      more internal functions/steps.
    * Obsolete and unused code is removed.

diff --git a/zlibs/bootstrap b/zlibs/bootstrap
--- a/zlibs/bootstrap
+++ b/zlibs/bootstrap
@@ -1,6 +1,7 @@
 #!/usr/bin/env zsh
+# shellcheck shell=bash
 # Copyright (c) 2016-2020 Dyne.org Foundation
-# libdevuansdk maintained by Ivan J. <parazyd@dyne.org>
+# libdevuansdk is maintained by Ivan J. <parazyd@dyne.org>
 #
 # This file is part of libdevuansdk
 #
@@ -17,222 +18,227 @@
 # You should have received a copy of the GNU General Public License
 # along with this source code. If not, see <http://www.gnu.org/licenses/>.
 
-vars+=(bootstrap_tgz_stage3 bootstrap_tgz_stage4 TAR_STAGE4)
-arrs+=(base_packages_option core_packages_option extra_packages_option)
-arrs+=(purge_packages_option)
+vars+=(bootstrap_cpio_stage3 bootstrap_cpio_stage4 CPIO_STAGE4)
 
-bootstrap_complete_base() {
-	fn bootstrap_complete_base "$@"
-	req=(arch)
+bootstrap_complete_base()
+{
+	fn bootstrap_complete_base "$*"
+	req=(R os arch strapdir LIBPATH release mirror)
 	ckreq || return 1
 
-	notice "bootstrapping $os $arch base"
+	notice "Bootstrapping: ${os}:${arch} base"
 
 	export LANG=C
 	export LC_ALL=C
 	export DEBIAN_FRONTEND=noninteractive
 
-	bootstrap_tgz_stage3="$R/tmp/bootstrap-${os}-${arch}-stage3.tgz"
-	bootstrap_tgz_stage4="$R/tmp/bootstrap-${os}-${arch}-stage4.tgz"
+	bootstrap_cpio_stage3="$R/tmp/bootstrap-${os}-${arch}-stage3.cpio.gz"
+	bootstrap_cpio_stage4="$R/tmp/bootstrap-${os}-${arch}-stage4.cpio.gz"
 
-	if [[ -n "$TAR_STAGE4" && -f "$bootstrap_tgz_stage4" ]]; then
-		notice "using the existing stage4 bootstrap tarball found in $R/tmp"
-		bootstrap_tar_unpack "$bootstrap_tgz_stage4" "$strapdir" || {
-			die "failed to extract tarball"
-			zerr
+	if [[ -n "$CPIO_STAGE4" && -f "$bootstrap_cpio_stage4" ]]; then
+		act "Using the existing stage4 bootstrap cpio archive..."
+		bootstrap_cpio_unpack "$bootstrap_cpio_stage4" "$strapdir" || {
+			die "Failed to extract cpio archive"
+			return 1
 		}
 		return
-	elif [[ -f "$bootstrap_tgz_stage3" ]]; then
-		notice "using the existing stage3 bootstrap tarball found in $R/tmp"
-		bootstrap_tar_unpack "$bootstrap_tgz_stage3" "$strapdir" || {
-			die "failed to extract tarball"
-			zerr
+	elif [[ -f "$bootstrap_cpio_stage3" ]]; then
+		act "Using the existing stage3 bootstrap cpio archive..."
+		bootstrap_cpio_unpack "$bootstrap_cpio_stage3" "$strapdir" || {
+			die "Failed to extract cpio archive"
+			return 1
 		}
+		bootstrap_stage4 || { zerr; return 1; }
+		if [[ -n "$CPIO_STAGE4" ]]; then
+			bootstrap_cpio_pack "$bootstrap_cpio_stage4" || { zerr; return 1; }
+		fi
 		return
 	fi
 
-	notice "running debootstrap stage 1"
+	notice "Running stage1 debootstrap"
 
-	sudo DEBOOTSTRAP_DIR="$LIBPATH/extra/debootstrap" "$LIBPATH/extra/debootstrap/debootstrap" \
+	sudo debootstrap \
 		--keyring="$LIBPATH/extra/devuan-keyring/keyrings/devuan-archive-keyring.gpg" \
-		--include=wget,ca-certificates \
+		--include=devuan-keyring,wget,ca-certificates \
 		--foreign \
-		--arch $arch $release $strapdir $mirror || zerr
+		--arch "$arch" "$release" "$strapdir" "$mirror" || { zerr; return 1; }
 
-	[[ $arch =~ "^arm.." ]] && { qemu_install_user || zerr }
-
-	sudo mkdir -p $strapdir/tmp
-	sudo chmod 1777 $strapdir/tmp
-
-	## debootstrap stage 2
-	notice "running debootstrap stage 2"
-	sudo chroot $strapdir \
-		/debootstrap/debootstrap --second-stage || zerr
-
-	blend_bootstrap_setup || zerr
-
-	## write all system configuration
-	notice "writing system configuration"
-	conf_print_debconf     | sudo tee $strapdir/debconf.set              >/dev/null
-	conf_print_fstab       | sudo tee $strapdir/etc/fstab                >/dev/null
-	conf_print_hostname    | sudo tee $strapdir/etc/hostname             >/dev/null
-	conf_print_hosts       | sudo tee $strapdir/etc/hosts                >/dev/null
-	conf_print_netifaces   | sudo tee $strapdir/etc/network/interfaces   >/dev/null
-	conf_print_resolvconf  | sudo tee $strapdir/etc/resolv.conf          >/dev/null
-	conf_print_sourceslist | sudo tee $strapdir/etc/apt/sources.list     >/dev/null
-	#conf_print_locales     | sudo tee $strapdir/etc/profile.d/locales.sh >/dev/null
-
-	## write third-stage for chroot
-	bootstrap_config_thirdstage | sudo tee $strapdir/thirdstage >/dev/null
-
-	## chroot into it and configure further
-	## debootstrap stage 3
-	notice "running debootstrap stage 3"
-
-
-	chroot-script -d thirdstage || zerr
-
-	[[ $APT_CACHE = 1 ]] && {
-		notice "adding apt cache gpg pubkey"
-		cat <<EOF | sudo tee ${strapdir}/addcachepubkey >/dev/null
-#!/bin/sh
-gpgkey="$(gpg --export -a $aptcachegpg)"
-printf "%s" "\$gpgkey" | apt-key add -
-EOF
-		chroot-script addcachepubkey || zerr
-	}
-
-	if [[ -n "$TAR_STAGE4" ]]; then
-		bootstrap_tar_pack   "$bootstrap_tgz_stage3"             || zerr
-		bootstrap_tar_unpack "$bootstrap_tgz_stage4" "$strapdir" || zerr
-	else
-		bootstrap_tar_pack   "$bootstrap_tgz_stage3"             || zerr
-		bootstrap_tar_unpack "$bootstrap_tgz_stage3" "$strapdir" || zerr
+	if [[ "$arch" =~ "^arm.." ]]; then
+		qemu_install_user "$strapdir" || { zerr; return 1; }
 	fi
+
+	notice "Running stage2 debootstrap"
+
+	sudo chroot "$strapdir" /debootstrap/debootstrap --second-stage || { zerr; return 1; }
+
+	# TODO: sys config as function
+	conf_print_fstab       | sudo tee "$strapdir/etc/fstab" >/dev/null
+	conf_print_hostname    | sudo tee "$strapdir/etc/hostname" >/dev/null
+	conf_print_hosts       | sudo tee "$strapdir/etc/hosts" >/dev/null
+	conf_print_netifaces   | sudo tee "$strapdir/etc/network/interfaces" >/dev/null
+	conf_print_resolvconf  | sudo tee "$strapdir/etc/resolv.conf" >/dev/null
+	conf_print_sourceslist | sudo tee "$strapdir/etc/apt/sources.list" >/dev/null
+
+	blend_bootstrap_setup || { zerr; return 1; }
+
+	bootstrap_stage3 || { zerr; return 1; }
+	bootstrap_cpio_pack "$bootstrap_cpio_stage3" || { zerr; return 1; }
+
+	bootstrap_stage4 || { zerr; return 1; }
+	if [[ -n "$CPIO_STAGE4" ]]; then
+		bootstrap_cpio_pack "$bootstrap_cpio_stage4" || { zerr; return 1; }
+	fi
+
+	return
 }
 
-bootstrap_config_thirdstage() {
-	fn bootstrap_config_thirdstage
-	req=(core_packages base_packages)
+bootstrap_stage3()
+{
+	fn bootstrap_stage3
+	req=(core_packages base_packages rootcredentials)
 	ckreq || return 1
 
-	cat << EOF
+	cat <<EOF | sudo tee "$strapdir/thirdstage" >/dev/null
 #!/bin/sh
 apt-get update
-debconf-set-selections /debconf.set
-
-echo "${rootcredentials}" | chpasswd
-sed -i -e 's/KERNEL\!=\"eth\*|/KERNEL\!=\"/' \
-	/lib/udev/rules.d/75-persistent-net-generator.rules
-rm -f /etc/udev/rules.d/70-persistent-net.rules
-export DEBIAN_FRONTEND=noninteractive
-
-apt-get --yes --force-yes install ${core_packages_option} ${core_packages}
-apt-get --yes --force-yes install ${base_packages_option} ${base_packages}
-apt-get --yes --force-yes purge  ${purge_packages_option} ${purge_packages}
-apt-get --yes --force-yes autoremove
-
+apt-get --yes --force-yes install ${core_packages_option} ${core_packages} || exit 1
+apt-get --yes --force-yes install ${base_packages_option} ${base_packages} || exit 1
+apt-get --yes --force-yes purge ${purge_packages_option} ${purge_packages} || exit 1
+apt-get --yes --force-yes --purge autoremove || exit 1
 apt-get clean
 
-sed -e 's/# en_US.UTF-8/en_US.UTF-8/' -i /etc/locale.gen
-locale-gen
+echo "${rootcredentials}" | chpasswd
 
-rm -f /debconf.set
 rm -f /etc/ssh/ssh_host_*
 rm -f /root/.bash_history
-#echo "1" > .keep
 EOF
+
+	chroot-script -d thirdstage || { zerr; return 1; }
 }
 
-bootstrap_tar_pack() {
-	fn bootstrap_tar_pack
-	req=(bootstrap_tgz)
-	bootstrap_tgz="$1"
+bootstrap_stage4()
+{
+	fn bootstrap_stage4
+	req=(strapdir extra_packages)
 	ckreq || return 1
 
-	local _dest="$(dirname $bootstrap_tgz)"
+	sudo mkdir -p "$strapdir"/{boot,dev,proc,sys}
 
-	if [[ -f "$bootstrap_tgz" ]]; then
-		notice "tarball found already in $_dest"
-	else
-		notice "Creating boostrap tarball in $bootstrap_tgz"
-		silly
-
-		pushd ${strapdir}
-		mkdir -p ${_dest}
-		silly
-		sudo tar czfp "$bootstrap_tgz" \
-			--acls \
-			--selinux \
-			--xattrs \
-			--xattrs-include=security.capability \
-			--xattrs-include=user.pax.flags \
-			--exclude={./dev,./sys,./proc} . || zerr
-		popd
-	fi
-}
-
-bootstrap_tar_unpack() {
-	fn bootstrap_tar_unpack $@
-	local bootstrap_tgz="$1"
-	req=(strapdir bootstrap_tgz)
-	ckreq || return 1
-
-	[[ -n "$TAR_STAGE4" ]] && {
-		[[ -f "$bootstrap_tgz" ]] || bootstrap_tgz="$bootstrap_tgz_stage3"
-	}
-	sudo rm -rf "${strapdir}"/*
-	silly
-	sudo tar xpf "$bootstrap_tgz" -C "$strapdir" --xattrs-include='*.*' --numeric-owner \
-		--acls --selinux --xattrs
-	sudo mkdir -p ${strapdir}/{boot,dev,sys,proc}
-
-	conf_print_sourceslist | sudo tee $strapdir/etc/apt/sources.list >/dev/null
-
-	cat <<EOF | sudo tee ${strapdir}/postunpack >/dev/null
+	cat <<EOF | sudo tee "$strapdir/fourthstage" >/dev/null
 #!/bin/sh
 apt-get update
 
-## check if all our extra_packages exist
+# check if all our extra_packages exist
 allpkgs="\$(apt-cache search '.' | cut -d' ' -f1)"
-for i in ${extra_packages} ; do
+for i in ${extra_packages}; do
 	printf "%s" "\$allpkgs" | grep -q "^\$i$" || {
 		case "\$i" in
-			--*) continue ;;
-			*)   missing="\$missing \$i" ;;
+		--*) continue;;
+		*)   missing="\$missing \$i" ;;
 		esac
 	}
 done
 
-[ -n "\$missing" ] && {
-	printf "\033[1;31m[!!] some extra packages don't exist\033[0m\n"
+if [ -n "\$missing" ]; then
+	printf "\033[1;31m[!!] Some extra packages don't exist:\033[0m\n"
 	printf "%s\n" "\$missing"
 	exit 1
-}
+fi
 
-apt-get --yes --force-yes upgrade
-apt-get --yes --force-yes install ${extra_packages_option} ${extra_packages}
-apt-get --yes --force-yes autoremove
-
+apt-get --yes --force-yes upgrade || exit 1
+apt-get --yes --force-yes install ${extra_packages_option} ${extra_packages} || exit 1
+apt-get --yes --force-yes --purge autoremove || exit 1
 apt-get clean
 EOF
 
-	chroot-script -d postunpack || zerr
+	chroot-script -d fourthstage || { zerr; return 1; }
 
 	for i in $inittab; do
-		grep -q "^$i" $strapdir/etc/inittab && continue
-		print "$i" | sudo tee -a $strapdir/etc/inittab >/dev/null
+		grep -q "$^i" "$strapdir/etc/inittab" && continue
+		echo "$i" | sudo tee -a "$strapdir/etc/inittab" >/dev/null
 	done || true
 
 	for i in $custmodules; do
-		grep -q "^$i" $strapdir/etc/modules && continue
-		print "$i" | sudo tee -a $strapdir/etc/modules >/dev/null
+		grep -q "^$i" "$strapdir/etc/modules" && continue
+		echo "$i" | sudo tee -a "$strapdir/etc/modules" >/dev/null
 	done || true
-
-	[[ -n "$TAR_STAGE4" ]] && bootstrap_tar_pack "$bootstrap_tgz_stage4" || true
 }
 
-blend_bootstrap_setup() {
-	fn blend_bootstrap_setup "noop"
-	return 0
+qemu_install_user()
+{
+	fn qemu_install_user "$*"
+	req=(arch _target)
+	local _target="$1"
+	ckreq || return 1
+
+	case "$(uname -m)" in
+	arm*|aarch*)
+		return
+		;;
+	esac
+
+	notice "Installing qemu-user-static"
+	case "$arch" in
+	armel)
+		sudo cp -a "$armel_qemu_bin" "$_target/usr/bin/" || { zerr; return 1; }
+		;;
+	armhf)
+		sudo cp -a "$armhf_qemu_bin" "$_target/usr/bin/" || { zerr; return 1; }
+		;;
+	arm64)
+		sudo cp -a "$arm64_qemu_bin" "$_target/usr/bin/" || { zerr; return 1; }
+		;;
+	esac
+}
+
+bootstrap_cpio_pack()
+{
+	fn bootstrap_cpio_pack "$*"
+	req=(_bootstrap_cpio strapdir)
+	local _bootstrap_cpio="$1"
+	ckreq || return 1
+
+	local _dest="$(dirname "$_bootstrap_cpio")"
+	if [[ -f "$_bootstrap_cpio" ]]; then
+		notice "cpio archive already found in $_dest"
+		return
+	fi
+
+	notice "Creating bootstrap cpio archive: $_bootstrap_cpio"
+	silly
+
+	pushd "$strapdir"
+	mkdir -p "$_dest"
+	sudo find . \
+		-not -path "./dev/*" \
+		-a -not -path "./proc/*" \
+		-a -not -path "./sys/*" \
+		| sudo cpio -o --format=newc \
+		| gzip - > "$_bootstrap_cpio" || { zerr; return 1; }
+	popd
+}
+
+bootstrap_cpio_unpack()
+{
+	fn bootstrap_cpio_unpack "$*"
+	req=(_bootstrap_cpio strapdir)
+	local _bootstrap_cpio="$1"
+	ckreq || return 1
+
+	notice "Unpacking bootstrap cpio archive: $_bootstrap_cpio"
+	silly
+
+	sudo rm -rf "${strapdir}"/*
+
+	pushd "$strapdir" || { zerr; return 1; }
+	zcat "$_bootstrap_cpio" | sudo cpio -id || { zerr; return 1; }
+	popd
+
+	sudo mkdir -p "$strapdir"/{boot,dev,proc,sys}
+}
+
+blend_bootstrap_setup()
+{
+	fn blend_bootstrap_setup "(noop)"
+	return
 }
diff --git a/zlibs/imaging b/zlibs/imaging
--- a/zlibs/imaging
+++ b/zlibs/imaging
@@ -1,4 +1,5 @@
 #!/usr/bin/env zsh
+# shellcheck shell=bash
 # Copyright (c) 2016-2020 Dyne.org Foundation
 # libdevuansdk is maintained by Ivan J. <parazyd@dyne.org>
 #
@@ -17,305 +18,337 @@
 # You should have received a copy of the GNU General Public License
 # along with this source code. If not, see <http://www.gnu.org/licenses/>.
 
-## imagine images
+vars+=(bootpart rootpart loopdevice)
 
-vars+=(image_name bootpart rootpart loopdevice filesystem)
-arrs+=(fsargs)
+strapdir_to_image()
+{
+	fn strapdir_to_image
+	req=(workdir strapdir bootpart rootpart loopdevice)
+	ckreq || return 1
 
-image_prepare_raw() {
+	notice "Copying strapdir to image ..."
+
+	if [[ ! -d "$workdir/mnt" ]]; then
+		die "$workdir/mnt doesn't exist. Did you run image_mount?"
+		zerr; return 1
+	fi
+
+	pushd "$strapdir"
+	sudo find . \
+		-not -path "./dev/*" \
+		-a -not -path "./proc/*" \
+		-a -not -path "./sys/*" \
+		| sudo cpio -p "$workdir/mnt" || { zerr; return 1; }
+	popd
+}
+
+image_prepare_raw()
+{
 	fn image_prepare_raw
 	req=(workdir size image_name)
 	ckreq || return 1
 
-	notice "creating raw image file from zeroes..."
-
-	dd if=/dev/zero \
-		of=$workdir/${image_name}.img \
-		bs=1M \
-		count=$size
+	notice "Creating raw image of $size MB"
+	touch "$workdir/${image_name}.img"
+	chattr +C "$workdir/${image_name}.img"
+	dd if=/dev/zero of="$workdir/${image_name}.img" bs=1M count="$size" || { zerr; return 1; }
 }
 
-image_format_partitions() {
+image_prepare_qcow2()
+{
+	fn image_prepare_qcow2
+	req=(workdir size image_name)
+	ckreq || return 1
+
+	notice "Creating qcow2 image of $size MB"
+	touch "$workdir/${image_name}.qcow2"
+	chattr +C "$workdir/${image_name}.qcow2"
+	qemu-img create -f qcow2 "${workdir}/${image_name}.qcow2" "${size}M" || { zerr; return 1; }
+}
+
+image_format_partitions()
+{
 	fn image_format_partitions
 	req=(bootfs bootpart rootpart)
 	ckreq || return 1
 
-	notice "formatting partitions..."
-	case "$bootfs" in
-		none)
-			act "skipping boot partition"
-			;;
-		vfat|fat|dos)
-			act "formatting boot as vfat"
-			sudo mkfs.vfat ${=bootopts} ${bootpart}
-			;;
-		ext4)
-			act "formatting boot as ext4"
-			sudo mkfs.ext4 ${=bootopts} ${bootpart}
-			;;
-		ext2)
-			act "formating boot as ext2"
-			sudo mkfs.ext2 ${=bootopts} ${bootpart}
-			;;
-		*)
-			error "unknown parted_bootfs type '$bootfs'"
-			zerr
-			;;
-	esac
+	notice "Formatting image partitions"
 
-	# default to ext4
-	[[ -z "$rootfs" ]] && rootfs=ext4
+	case "$bootfs" in
+	none)
+		act "Skipping boot partition"
+		;;
+	vfat|fat|dos)
+		act "Formatting boot as VFAT"
+		sudo mkfs.vfat ${=bootopts} "${bootpart}" || { zerr; return 1; }
+		;;
+	ext?)
+		act "Formatting boot as $bootfs"
+		sudo mkfs.${bootfs} ${=bootopts} "${bootpart}" || { zerr; return 1; }
+		;;
+	btrfs)
+		act "Formatting boot as btrfs"
+		sudo mkfs.btrfs ${=bootopts} "${bootpart}" || { zerr; return 1; }
+		;;
+	"")
+		die "No bootfs filesystem set!"
+		zerr; return 1
+		;;
+	*)
+		die "Unimplemented filesystem: $bootfs"
+		die "Please report it for inclusion."
+		zerr; return 1
+		;;
+	esac
 
 	case "$rootfs" in
-		none)
-			act "skipping root partition"
-			;;
-		vfat|fat|dos)
-			act "formatting root as vfat"
-			sudo mkfs.vfat ${=rootopts} ${rootpart}
-			;;
-		ext4)
-			act "formatting root as ext4"
-			sudo mkfs.ext4 ${=rootopts} ${rootpart}
-			;;
-		ext2)
-			act "formating root as ext2"
-			sudo mkfs.ext2 ${=rootopts} ${rootpart}
-			;;
-		btrfs)
-			act "formatting root as btrfs"
-			sudo mfks.btrfs ${=rootopts} ${rootpart}
-			;;
-		*)
-			error "unknown parted_rootfs type '$rootfs'"
-			zerr
-			;;
+	none)
+		act "Skipping root partition"
+		;;
+	vfat|fat|dos)
+		act "Formatting root as VFAT"
+		sudo mkfs.vfat ${=rootopts} "${rootpart}" || { zerr; return 1; }
+		;;
+	ext?)
+		act "Formatting root as $rootfs"
+		sudo mkfs.${rootfs} ${=rootopts} "${rootpart}" || { zerr; return 1; }
+		;;
+	btrfs)
+		act "Formatting root as btrfs"
+		sudo mkfs.btrfs ${=rootopts} "${rootpart}" || { zerr; return 1; }
+		;;
+	"")
+		die "No rootfs filesystem set!"
+		zerr; return 1
+		;;
+	*)
+		die "Unimplemented filesystem: $rootfs"
+		die "Please report it for inclusion."
+		zerr; return 1
+		;;
 	esac
 }
 
-image_partition_raw_dos() {
-	fn image_partition_raw_dos
-	req=(workdir image_name parted_boot parted_root)
+image_connect_raw()
+{
+	fn image_connect_raw
+	req=(workdir image_name)
 	ckreq || return 1
 
-	notice "partitioning raw dos image..."
+	notice "Connecting raw image to loop device"
 
-	parted $workdir/${image_name}.img --script -- mklabel msdos
-	parted $workdir/${image_name}.img --script -- mkpart primary ${parted_boot}
-	parted $workdir/${image_name}.img --script -- mkpart primary ${parted_root}
-	[ -n "$bootable_part" ] && \
-		parted "$workdir/${image_name}.img" --script -- set "$bootable_part" boot on
-
-	## get loopdevice (see ./helpers)
-	findloopdev
-
-	bootpart=${loopdevice}p1
-	rootpart=${loopdevice}p2
-
-	image_format_partitions
-}
-
-image_partition_raw_gpt() {
-	fn image_partition_raw_gpt
-	req=(workdir image_name gpt_boot gpt_root)
-	ckreq || return 1
-
-	notice "partitioning raw gpt image..."
-
-	parted $workdir/${image_name}.img --script -- mklabel gpt || zerr
-	cgpt create -z $workdir/${image_name}.img || zerr
-	cgpt create    $workdir/${image_name}.img || zerr
-
-	cgpt add -i 1 -t kernel -b ${gpt_boot[1]} \
-		-s ${gpt_boot[2]} \
-		-l kernel -S 1 -T 5 -P 10 $workdir/${image_name}.img
-
-	cgpt add -i 2 -t data -b ${gpt_root[1]} \
-		-s $(expr $(cgpt show $workdir/${image_name}.img | \
-		awk '/Sec GPT table/ {print $1}') - ${gpt_root[1]}) \
-		-l Root $workdir/${image_name}.img
-
-	findloopdev
+	loopdevice="$(findloopdev)"
+	if [[ -z "$loopdevice" ]]; then
+		die "Didn't find a free loop device"
+		zerr; return 1
+	fi
 
 	bootpart="${loopdevice}p1"
 	rootpart="${loopdevice}p2"
-
-	image_format_partitions
 }
 
-image_pack_dist() {
-	fn image_pack_dist
-	req=(loopdevice image_name strapdir workdir)
+image_connect_qcow2()
+{
+	fn image_connect_qcow2
+	req=(workdir image_name)
 	ckreq || return 1
 
-	notice "packaging image for dist"
+	notice "Connecting qcow2 image to nbd device"
 
-	act "rechecking filesystem"
-	sudo e2fsck -fy ${loopdevice}p2
-	sudo resize2fs ${loopdevice}p2
-
-	sleep 2
-
-	[[ $parted_type = gpt ]] && {
-		sudo cgpt repair $loopdevice
-		sleep 1
-	}
-
-	case "$device_name" in
-		pinephone-dontbeevil)
-			notice "dd-ing u-boot bootloader to image"
-			sudo dd if="$R/dist/u-boot-sunxi-with-spl-sopine.bin" \
-				of="$loopdevice" bs=1024 seek=8 || zerr
-			;;
-	esac
-
-	sudo partx -dv $loopdevice || {
-		die "partx failed to remove $loopdevice"
-		zerr
-	}
-	sudo losetup -d $loopdevice || {
-		die "losetup failed to remove $loopdevice"
-		zerr
-	}
-
-	if [[ -n "$nocompressimage" ]]; then
-		_suffix="img"
-	else
-		_suffix="img.xz"
+	sudo modprobe nbd max_part=8 || { zerr; return 1; }
+	loopdevice="$(findnbddev)"
+	if [[ -z "$loopdevice" ]]; then
+		die "Didn't find a free nbd device"
+		zerr; return 1
 	fi
 
-	pushd $workdir
-
-	[[ -n "$nocompressimage" ]] || {
-		if which pixz > /dev/null ; then
-			xzcomp=$(which pixz)
-		else
-			xzcomp=$(which xz)
-		fi
-
-		notice "compressing image with $xzcomp"
-		silly
-
-		$xzcomp "${image_name}.img"
-	}
-
-	mkdir -p "$R/dist"
-	mv -v ${image_name}.${_suffix} $R/dist/
-
-	pushd "$R/dist"
-	notice "generating sha256 for ${image_name}.${_suffix}"
-	sha256sum ${image_name}.${_suffix} > ${image_name}.${_suffix}.sha
-	notice "generating sha256 for ${image_name}.tar.gz"
-	sha256sum ${image_name}.tar.gz > ${image_name}.tar.gz.sha
-	popd
-
-	popd
-
-	[[ $DEBUG = 1 ]] || sudo rm -r $workdir
-
-	notice "finished packing $image_name"
-	act "find it in $R/dist/"
-	act "thanks for being patient!"
+	sudo qemu-nbd --connect="${loopdevice}" "$workdir/${image_name}.qcow2" || { zerr; return 1; }
 }
 
-image_raw_mount() {
-	fn image_raw_mount
+image_partition_dos()
+{
+	fn image_partition_dos
+	req=(loopdevice bootpart rootpart dos_boot dos_root)
+	ckreq || return 1
+
+	notice "Partitioning dos image"
+
+	sudo parted "$loopdevice" --script -- mklabel msdos || { zerr; return 1; }
+	sudo parted "$loopdevice" --script -- mkpart primary "$dos_boot" || { zerr; return 1; }
+	sudo parted "$loopdevice" --script -- mkpart primary "$dos_root" || { zerr; return 1; }
+	if [[ -n "$bootable_part" ]]; then
+		sudo parted "$loopdevice" --script -- set "$bootable_part" boot on
+	fi
+
+	sudo partprobe "$loopdevice" || { zerr; return 1; }
+}
+
+image_mount()
+{
+	fn image_mount
 	req=(workdir bootpart rootpart bootfs)
 	ckreq || return 1
 
-	mkdir -p $workdir/mnt
-	sudo mount $rootpart $workdir/mnt && \
-		act "mounted root partition" || zerr
+	notice "Mounting image to $workdir/mnt"
 
-	[[ "$bootfs" == none ]] || {
-		sudo mkdir -p $workdir/mnt/boot
-		sudo mount $bootpart $workdir/mnt/boot && \
-			act "mounted boot partition" || zerr
-	}
+	mkdir -p "$workdir/mnt"
+	sudo mount "$rootpart" "$workdir/mnt" || { zerr; return 1; }
+	act "Mounted root partition"
+
+	if [[ "$bootfs" = none ]]; then
+		return
+	fi
+
+	sudo mkdir -p "$workdir/mnt/boot"
+	sudo mount "$bootpart" "$workdir/mnt/boot" || { zerr; return 1; }
+	act "Mounted boot partition"
 }
 
-image_raw_umount() {
-	fn image_raw_umount
+image_umount()
+{
+	fn image_umount
 	req=(workdir bootpart rootpart)
 	ckreq || return 1
 
-	[[ "$bootfs" == none ]] || {
-		sudo umount $workdir/mnt/boot && act "unmounted boot partition" || zerr
-		sleep 1
+	notice "Umounting image from $workdir/mnt"
+
+	sudo umount -R "$workdir/mnt" || { zerr; return 1; }
+	act "Umounted"
+
+	act "Flushing bytes and buffers"
+	sudo blockdev --flushbufs "$loopdevice" || { zerr; return 1; }
+	sudo python -c 'import os; os.fsync(open("'$loopdevice'", "r+b"))' || { zerr; return 1; }
+}
+
+image_disconnect_raw()
+{
+	fn image_disconnect_raw
+	req=(loopdevice bootfs rootfs bootpart rootpart)
+	ckreq || return 1
+
+	notice "Disconnecting image from $loopdevice"
+
+	act "Rechecking filesystems"
+	case "$bootfs" in
+	ext?)
+		sudo e2fsck -fy "$bootpart"
+		sudo resize2fs "$bootpart"
+		;;
+	esac
+
+	case "$rootfs" in
+	ext?)
+		sudo e2fsck -fy "$rootpart"
+		sudo resize2fs "$rootpart"
+		;;
+	esac
+
+	act "Disconnecting"
+	sudo partx -dv "$loopdevice" || {
+		die "partx failed to remove $loopdevice"
+		zerr; return 1
 	}
-	sudo umount $workdir/mnt      && act "unmounted root partition" || zerr
+
+	sudo losetup -d "$loopdevice" || {
+		die "losetup failed to remove $loopdevice"
+		zerr; return 1
+	}
 }
 
-image_raw_as_strapdir() {
-	fn image_raw_as_strapdir
-	req=(workdir strapdir size)
+image_disconnect_qcow2()
+{
+	fn image_disconnect_qcow2
+	req=(loopdevice bootfs rootfs bootpart rootpart)
 	ckreq || return 1
 
-	pushd "$workdir"
+	notice "Disconnecting image from $loopdevice"
 
-	notice "creating raw image of $size MB"
-	sudo rm -f base.raw
-	sudo qemu-img create -f raw base.raw ${size}M   || zerr
-	notice "partitioning"
-	sudo parted base.raw mktable msdos              || zerr
-	sudo parted base.raw mkpart primary '0%' '100%' || zerr
-	loopdevice=$(losetup --find)
-	sudo losetup -P $loopdevice base.raw || zerr
-	sudo mkfs.ext4 ${loopdevice}p1       || zerr
+	act "Rechecking filesystems"
+	case "$bootfs" in
+	ext?)
+		sudo e2fsck -fy "$bootpart"
+		sudo resize2fs "$bootpart"
+		;;
+	esac
 
-	notice "mounting raw image to strapdir"
-	sudo mount ${loopdevice}p1 $strapdir
-	echo 1 | sudo tee ${strapdir}/.keep >/dev/null
+	case "$rootfs" in
+	ext?)
+		sudo e2fsck -fy "$rootpart"
+		sudo resize2fs "$rootpart"
+		;;
+	esac
+
+	act "Disconnecting"
+
+	sudo qemu-nbd --disconnect "$loopdevice" || { zerr; return 1; }
+}
+
+image_raw_to_qcow2()
+{
+	fn image_raw_to_qcow2
+	req=(image_name workdir)
+	ckreq || return 1
+
+	notice "Converting raw image to qcow2"
+	pushd "$workdir" || { zerr; return 1; }
+	touch "${image_name}.qcow2"
+	chattr +C "${image_name}.qcow2"
+	qemu-img convert -f raw -O qcow2 "${image_name}.img" "${image_name}.qcow2" || { zerr; return 1; }
 	popd
 }
 
-image_qcow2_as_strapdir() {
-	fn image_qcow2_as_strapdir
-	req=(workdir strapdir size)
+image_raw_to_vdi()
+{
+	fn image_raw_to_vdi
+	req=(image_name workdir)
 	ckreq || return 1
 
-	pushd "$workdir"
-
-	# default filesystem fallback to ext4
-	filesystem=${filesystem:-ext4}
-
-	notice "creating qcow2 image of $size MB formatted with $filesystem"
-	rm -f base.qcow2
-	qemu-img create -f qcow2 base.qcow2 ${size}M     || zerr
-	sudo modprobe nbd max_part=8                     || zerr
-	loopdevice="$(findfreenbd)"
-	[ -n "$loopdevice" ]                             || zerr
-	act "$loopdevice"
-	sudo qemu-nbd --connect=${loopdevice} base.qcow2 || zerr
-
-	notice "partitioning"
-	sudo parted ${loopdevice} mktable msdos              || zerr
-	sudo parted ${loopdevice} mkpart primary '0%' '100%' || zerr
-
-	notice "formatting with $filesystem"
-	command -v mkfs.${filesystem} >/dev/null || {
-		error "filesystem tools not found in path: mkfs.${filesystem}"
-		zerr }
-	sudo mkfs.${filesystem} ${=fsargs} ${loopdevice}p1 || zerr
-
-	notice "mounting qcow2 image to strapdir"
-	sudo mount ${loopdevice}p1 $strapdir || zerr
-	echo 1 | sudo tee ${strapdir}/.keep >/dev/null
+	notice "Converting raw image to vdi"
+	pushd "$workdir" || { zerr; return 1; }
+	touch "${image_name}.vdi"
+	chattr +C "${image_name}.vdi"
+	qemu-img convert -f raw -O vdi "${image_name}.img" "${image_name}.vdi" || { zerr; return 1; }
+	#VBoxManage modifyhd "${image_name}.vdi" --type immutable --compact || { zerr; return 1; }
 	popd
 }
 
-tar_strapdir() {
-	fn tar_strapdir
-	req=(strapdir)
+image_pack_dist()
+{
+	fn image_pack_dist
+	req=(R image_name workdir)
 	ckreq || return 1
 
-	notice "creating a tarbomb of the rootfs..."
-	mkdir -p "$R/dist"
+	notice "Packing up built images"
+
+	local _xzcomp=""
+	local _rsuffix="img"
+
+	if [[ -n "$COMPRESS_IMAGE" ]]; then
+		if command -v pixz >/dev/null; then
+			_xzcomp="$(command -v pixz)"
+		else
+			_xzcomp="$(command -v xz)"
+		fi
+		_rsuffix="img.xz"
+	fi
+
+	pushd "$workdir" || { zerr; return 1; }
+
+	if [[ -n "$COMPRESS_IMAGE" ]]; then
+		act "Compressing images with $_xzcomp"
+		silly
+		$_xzcomp "${image_name}.img" || { zerr; return 1; }
+		# TODO: cpio image?
+	fi
+
+	act "Calculating sha256 checksums"
 	silly
-	pushd "$strapdir"
-	sudo tar czf "$R/dist/${image_name}.tar.gz" . \
-		--acls --selinux --xattrs \
-		--xattrs-include=security.capability \
-		--xattrs-include=user.pax.flags || zerr
+	sha256sum "${image_name}.${_rsuffix}" > "${image_name}.${_rsuffix}.sha256"
+	# TODO: cpio image?
+	mkdir -p "$R/dist"
+	mv -v "${image_name}".* "$R/dist" || { zerr; return 1; }
+
+	notice "Done! Thanks for being patient!"
+
 	popd
 }
